kind: Service                             
apiVersion: v1
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
    - port: 8080                               
      targetPort: 8080                    
      nodePort: 31200
  selector:
    app: webapp
  type: LoadBalancer                   
